name: mmat-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22
  - pandas>=1.4
  - scikit-learn>=1.0
  - xgboost>=1.6
  - joblib
  - matplotlib>=3.5
  - seaborn>=0.11
  - plotly>=5.6
  - python-binance
  - python-dotenv
  - tqdm
  - ta-lib
  - pip
