name: mmat-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - numpy=2.2.6
  - pandas=2.3.0
  - scikit-learn=1.7.0
  - xgboost=3.0.2
  - joblib=1.5.1
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - plotly=6.2.0
  - python-dotenv=1.1.1
  - tqdm=4.67.1
  - ta-lib=0.5.1
  - pip=25.1.1
  - pip:
      - python-binance==1.0.29